### ISSUE TITLE
4.5 - doesn't work

### ISSUE THREAD

**Issue by aspark21** [Peterburnett/moodle-tool_forcedcache#57]
I had to pull our forced cache config and this plugin 4.5 to get the test instance to load

I'm assuming it was related to the major change in https://tracker.moodle.org/browse/MDL-66151

<img width="643" alt="Screenshot 2024-09-03 at 13 41 53" src="https://github.com/user-attachments/assets/1380b003-2cbd-4972-8298-0c3f1350d98b">

**Comment by danmarsden** [comment]
I've just pushed a 4.5 branch into the repo that works for us here - I didn't hit the sessions table not existing error but you might be using a diffrent caching config to us. it would be good for you to check if the new branch fixes it.

**Comment by aspark21** [comment]
I’ll take a look but I think I have an idea of how this happened due to encountering other weird behaviour in the run up to https://tracker.moodle.org/browse/MDLQA-19085

Assuming instance is already setup and running on 4.4 with the forced cache config enforcing.

When new (4.5) code is deployed and even with updated config.php some of this config is getting cached and the 4.4 enforcing is still applying.

Once admin has logged in and triggers cache purge, during initial load of admin/index.php upgrade screen, then the new config gets picked up. 

I noticed this with the QA tracker because I re-used the test site from a blank database to a restore from prod db. But while the site name had fed through, the auth was still only manual & OIDC (Entra ID) was supposedly a disabled plugin. As soon as hit that first screen of the upgrade process, I could see theme applied & auth was now enabled.

I don’t know if it’s a new thing or just the way caching has always been (I assume the later)

But in this context, the solution might just be  to add a mention that users will need to explicitly purge cache manually before trying to upgrade a site through web interface.


The reason I would have had to do that full clear out originally might well be because removing the plugin code, forced the triggering of the cache purge

**Comment by brendanheywood** [comment]
I've hit another issue in 4.5

https://master.localhost/admin/tool/heartbeat/status.php

Exception - Failed opening required '[dirroot]/admin/tool/forcedcache/classes/../../../../cache/locallib.php' (include_path='[dirroot]/lib/pear:.:/usr/share/php')

[More information about this error](https://docs.moodle.org/500/en/error/moodle/generalexceptionmessage)

Debug info:
Error code: generalexceptionmessage×Dismiss this notification
Stack trace:
line 19 of /admin/tool/forcedcache/classes/cache_config_writer.php: Error thrown
line 217 of /lib/classes/component.php: call to include_once()
line 250 of /admin/tool/forcedcache/classes/cache_config.php: call to core\component::classloader()
line 95 of /admin/tool/forcedcache/classes/cache_config.php: call to tool_forcedcache_cache_config->generate_store_instance_config()
line 64 of /admin/tool/forcedcache/classes/cache_config.php: call to tool_forcedcache_cache_config->generate_config_array()
line 43 of /admin/tool/forcedcache/classes/cache_config.php: call to tool_forcedcache_cache_config->include_configuration()
line 59 of /admin/tool/forcedcache/classes/check/enabled.php: call to tool_forcedcache_cache_config->get_inclusion_errors()
line 317 of /admin/tool/heartbeat/classes/checker.php: call to tool_forcedcache\check\enabled->get_result()
line 71 of /admin/tool/heartbeat/classes/table/status_table.php: call to tool_heartbeat\checker::get_overridden_result()
line 39 of /admin/tool/heartbeat/status.php: call to tool_heartbeat\table\status_table->render()

**Comment by aspark21** [comment]
I have gone through a 4.5 dry. run upgrade with the MOODLE_405_STABLE branch of focedcache and I can confirm all worked well this time.

Closing as fixed :)
